trigger:
- master

# Since we use LocalDB for the test database, it must run in a Windows environment
pool:
  vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  displayName: Require .NET 2.1 runtime for RoundHousE
  inputs:
    packageType: 'runtime'
    version: '2.1.x'

- task: UseDotNet@2
  displayName: Require .NET 3.1 SDK for Build Process
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: PowerShell@2
  displayName: Setup Required Dependencies
  inputs:
    filePath: 'setup.ps1'

- task: PowerShell@2
  displayName: Generate Version using GitVersion
  inputs:
    targetType: 'inline'
    script: dotnet gitversion /output buildserver

- task: PowerShell@2
  displayName: Build and Test
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: 'invoke-psake ci -properties ${''version'':''$(Build.BuildNumber)''}'
  
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**.trx'
    searchFolder: 'TestResults'
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'publish'
    artifact: 'website'
    publishLocation: 'pipeline'
    